{% set name = "zope.hookable" %}
{% set version = "5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c3018bcf2b39cf5cccf40826f799b4b8c140056db780f96cb0ca332a243bd29

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - zope.proxy

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/zopefoundation/zope.hookable
  license: ZPL-2.1
  license_file: LICENSE.txt
  summary: supports the efficient creation of “hookable” objects, which are callable objects that are meant to be optionally replaced.
  description: |
    This package supports the efficient creation of “hookable” objects, which
    are callable objects that are meant to be optionally replaced.
    The idea is that you create a function that does some default thing and make
    it hookable. Later, someone can modify what it does by calling its sethook
    method and changing its implementation. All users of the function, including
    those that imported it, will see the change.
  doc_url: https://zopehookable.readthedocs.io
  dev_url: https://github.com/zopefoundation/zope.hookable

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - daf
